# Generated by Django 4.1 on 2025-01-05 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0008_remove_cliente_estado_cliente_status'),
        ('direccion', '0002_alter_estado_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimuladorSolicitudView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_energia_ahorrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_id', models.IntegerField()),
                ('estado_id', models.IntegerField()),
                ('estado', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Simulador Solicitud',
                'verbose_name_plural': 'Simulador Solicitudes',
                'db_table': 'simulador_solicitud_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_kwh', models.IntegerField(verbose_name='Consumo (kWh)')),
                ('pago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pago')),
                ('estdo_name', models.CharField(max_length=50)),
                ('cantidad_energia_ahorrada', models.IntegerField(verbose_name='Cantidad de energía a ahorrar %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.estado', verbose_name='Estado')),
            ],
        ),
    ]
