# Generated by Django 4.1 on 2024-12-13 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_kwh', models.IntegerField(verbose_name='Consumo (kWh)')),
                ('pago', models.DateField(verbose_name='Pago')),
                ('estdo_name', models.CharField(max_length=50)),
                ('cantidad_energia_ahorrada', models.IntegerField(verbose_name='Cantidad de energía a ahorrar %')),
                ('created_at', models.IntegerField(max_length=11, verbose_name='Fecha de creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='direccion.estado', verbose_name='Estado')),
            ],
        ),
    ]
