# Generated by Django 4.1 on 2024-12-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='created_at',
            field=models.IntegerField(verbose_name='Fecha de creación'),
        ),
    ]
