[env]
pythonVersion = "3.12"

[build]
# Instalar paquetes necesarios para dependencias
setup = """
sudo apt-get update && sudo apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    libmysqlclient-dev
"""
