# Generated by Django 4.1 on 2024-12-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopostal',
            name='codigo_postal',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='colonia',
            name='d_asenta',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='estado',
            name='clave',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
