# Generated by Django 4.1 on 2024-12-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'permissions': [('can_view', 'VER estado'), ('can_update', 'ACTUALIZAR estado')], 'verbose_name_plural': 'Estados'},
        ),
    ]
