# Generated by Django 4.1 on 2024-12-12 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.IntegerField(default=None, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.IntegerField(default=None, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(max_length=200, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(max_length=200, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
