# Generated by Django 4.1 on 2024-12-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_amigos_usuario_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.IntegerField(default=None, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.IntegerField(default=None, null=True, verbose_name='Fecha de actualización'),
        ),
    ]
