# Generated by Django 4.1 on 2024-12-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_user', 'VER USUARIO'), ('can_update_user', 'ACTUALIZAR USUARIO'), ('can_create_user', 'CREAR USUARIO')]},
        ),
    ]
