# Generated by Django 4.1 on 2024-12-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.IntegerField(choices=[(10, 'LEAD'), (20, 'CLIENTE')], default=10, verbose_name='Tipo'),
        ),
    ]
