# Generated by Django 4.1 on 2024-12-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_estado_cliente_fecha_nacimiento_cliente_giro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(default=None, max_length=150, verbose_name='Apellidos materno '),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(default=None, max_length=150, verbose_name='Apellido paterno '),
        ),
    ]
