# Generated by Django 4.1 on 2024-12-25 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_apellidos_cliente_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('can_view_cliente', 'VER USUARIO'), ('can_update_cliente', 'ACTUALIZAR USUARIO'), ('can_create_cliente', 'CREAR USUARIO'), ('can_delete_cliente', 'ELIMINAR USUARIO')]},
        ),
    ]
