# Generated by Django 4.1 on 2024-12-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('can_view_cliente', 'VER CLIENTE'), ('can_update_cliente', 'ACTUALIZAR CLIENTE'), ('can_create_cliente', 'CREAR CLIENTE'), ('can_delete_cliente', 'ELIMINAR CLIENTE')]},
        ),
        migrations.RenameField(
            model_name='direccionclientes',
            old_name='usuario',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
